# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import annotation_pb2 as annotation__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in annotation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DpAnnotationServiceStub(object):
    """
    ------------------- RPC Interfaces ---------------------------



    Annotation Service Interface

    Interface for annotating archived data.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.saveDataSet = channel.unary_unary(
                '/dp.service.annotation.DpAnnotationService/saveDataSet',
                request_serializer=annotation__pb2.SaveDataSetRequest.SerializeToString,
                response_deserializer=annotation__pb2.SaveDataSetResponse.FromString,
                _registered_method=True)
        self.queryDataSets = channel.unary_unary(
                '/dp.service.annotation.DpAnnotationService/queryDataSets',
                request_serializer=annotation__pb2.QueryDataSetsRequest.SerializeToString,
                response_deserializer=annotation__pb2.QueryDataSetsResponse.FromString,
                _registered_method=True)
        self.saveAnnotation = channel.unary_unary(
                '/dp.service.annotation.DpAnnotationService/saveAnnotation',
                request_serializer=annotation__pb2.SaveAnnotationRequest.SerializeToString,
                response_deserializer=annotation__pb2.SaveAnnotationResponse.FromString,
                _registered_method=True)
        self.queryAnnotations = channel.unary_unary(
                '/dp.service.annotation.DpAnnotationService/queryAnnotations',
                request_serializer=annotation__pb2.QueryAnnotationsRequest.SerializeToString,
                response_deserializer=annotation__pb2.QueryAnnotationsResponse.FromString,
                _registered_method=True)
        self.exportData = channel.unary_unary(
                '/dp.service.annotation.DpAnnotationService/exportData',
                request_serializer=annotation__pb2.ExportDataRequest.SerializeToString,
                response_deserializer=annotation__pb2.ExportDataResponse.FromString,
                _registered_method=True)


class DpAnnotationServiceServicer(object):
    """
    ------------------- RPC Interfaces ---------------------------



    Annotation Service Interface

    Interface for annotating archived data.
    """

    def saveDataSet(self, request, context):
        """
        saveDataSet: Create or update a DataSet.

        This RPC sends a request to the annotation service to save a DataSet with the specified parameters.
        The annotation service performs validation, and for a valid request, it performs an "upsert" (insert or update)
        for the specified DataSet. The response may indicate rejection, an error in handling the request,
        or successful handling of the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def queryDataSets(self, request, context):
        """
        queryDataSets: Unary (non-streaming) data sets query.

        This RPC returns information about DataSets matching the specified query parameters. Client sends a single
        QueryDataSetsRequest and receives a single QueryDataSetsResponse. The response may indicate rejection,
        error in handling, no data matching query, or otherwise contains the data matching the query specification.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def saveAnnotation(self, request, context):
        """
        saveAnnotation

        This RPC sends a request to the annotation service to create or update an annotation with the
        specified parameters. The annotation service performs validation, and for a valid request,
        attempts to "upsert" the annotation. The response may indicate rejection, an error in handling the request,
        or successful handling of the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def queryAnnotations(self, request, context):
        """
        queryAnnotations: Unary (non-streaming) annotations query.

        This RPC is used by clients to query over annotations added to ingested data.
        Client sends a single QueryAnnotationsRequest with the query parameters, and receives a single
        QueryAnnotationsResponse with the query results. The response may indicate rejection, error in handling,
        no data matching query, or otherwise contains the data matching the query specification.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def exportData(self, request, context):
        """
        exportData(): Export data to common file formats.

        This RPC is used by clients to export data (both DataSets and Calculations) to file.  Client sends a single
        ExportDataRequest specifying the details of the data to be exported and the desired output file format,
        and receives a single response.  The response may indicate a problem handling the request, or otherwise contains
        details about the exported file including the path and optional (if configured) URL for accessing the file.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DpAnnotationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'saveDataSet': grpc.unary_unary_rpc_method_handler(
                    servicer.saveDataSet,
                    request_deserializer=annotation__pb2.SaveDataSetRequest.FromString,
                    response_serializer=annotation__pb2.SaveDataSetResponse.SerializeToString,
            ),
            'queryDataSets': grpc.unary_unary_rpc_method_handler(
                    servicer.queryDataSets,
                    request_deserializer=annotation__pb2.QueryDataSetsRequest.FromString,
                    response_serializer=annotation__pb2.QueryDataSetsResponse.SerializeToString,
            ),
            'saveAnnotation': grpc.unary_unary_rpc_method_handler(
                    servicer.saveAnnotation,
                    request_deserializer=annotation__pb2.SaveAnnotationRequest.FromString,
                    response_serializer=annotation__pb2.SaveAnnotationResponse.SerializeToString,
            ),
            'queryAnnotations': grpc.unary_unary_rpc_method_handler(
                    servicer.queryAnnotations,
                    request_deserializer=annotation__pb2.QueryAnnotationsRequest.FromString,
                    response_serializer=annotation__pb2.QueryAnnotationsResponse.SerializeToString,
            ),
            'exportData': grpc.unary_unary_rpc_method_handler(
                    servicer.exportData,
                    request_deserializer=annotation__pb2.ExportDataRequest.FromString,
                    response_serializer=annotation__pb2.ExportDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dp.service.annotation.DpAnnotationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dp.service.annotation.DpAnnotationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DpAnnotationService(object):
    """
    ------------------- RPC Interfaces ---------------------------



    Annotation Service Interface

    Interface for annotating archived data.
    """

    @staticmethod
    def saveDataSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dp.service.annotation.DpAnnotationService/saveDataSet',
            annotation__pb2.SaveDataSetRequest.SerializeToString,
            annotation__pb2.SaveDataSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def queryDataSets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dp.service.annotation.DpAnnotationService/queryDataSets',
            annotation__pb2.QueryDataSetsRequest.SerializeToString,
            annotation__pb2.QueryDataSetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def saveAnnotation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dp.service.annotation.DpAnnotationService/saveAnnotation',
            annotation__pb2.SaveAnnotationRequest.SerializeToString,
            annotation__pb2.SaveAnnotationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def queryAnnotations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dp.service.annotation.DpAnnotationService/queryAnnotations',
            annotation__pb2.QueryAnnotationsRequest.SerializeToString,
            annotation__pb2.QueryAnnotationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def exportData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dp.service.annotation.DpAnnotationService/exportData',
            annotation__pb2.ExportDataRequest.SerializeToString,
            annotation__pb2.ExportDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
