# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ingestion_stream_pb2 as ingestion__stream__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ingestion_stream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DpIngestionStreamServiceStub(object):
    """
    ------------------- RPC Interfaces ---------------------------



    The Ingestion Stream Service Interface

    Defines RPC operations for processing of the ingestion data stream.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.subscribeDataEvent = channel.stream_stream(
                '/dp.service.ingestionstream.DpIngestionStreamService/subscribeDataEvent',
                request_serializer=ingestion__stream__pb2.SubscribeDataEventRequest.SerializeToString,
                response_deserializer=ingestion__stream__pb2.SubscribeDataEventResponse.FromString,
                _registered_method=True)


class DpIngestionStreamServiceServicer(object):
    """
    ------------------- RPC Interfaces ---------------------------



    The Ingestion Stream Service Interface

    Defines RPC operations for processing of the ingestion data stream.

    """

    def subscribeDataEvent(self, request_iterator, context):
        """
        subscribeDataEvent()

        This method allows the client to register a subscription for a data event, and receive notification when new data
        is received by the Ingestion Service that triggers the specified event.  The method uses bidirectional streaming,
        where the client sends a stream of SubscribeDataEventRequest messages and receives a stream of
        SubscribeDataEventResponse messages in the response stream.

        To initiate a new subscription, the client sends a SubscribeDataEventRequest message with a NewSubscription
        payload specifying the details for the data event to be monitored.

        The service responds with a single SubscribeDataEventResponse message, containing either an ExceptionalResult
        message payload if the request is rejected by the service or an AckResult message if the service accepts the
        request and registers the subscription.

        The service then sends a stream of SubscribeDataEventResponse messages, each containing either Event or EventData
        message payloads.

        There are two mechanisms for canceling a data event subscription. To explicitly cancel a subscription, the client
        sends a SubscribeDataEventRequest message containing a CancelSubscription message payload.  The client can also
        implicitly cancel a subscription by simply closing the API method request stream.

        The service sends a response with an ExceptionalResult payload if it rejects the subscription request or an error
        occurs while handling the subscription.  In either case, after sending the ExceptionalResult message the service
        closes the API method response stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DpIngestionStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'subscribeDataEvent': grpc.stream_stream_rpc_method_handler(
                    servicer.subscribeDataEvent,
                    request_deserializer=ingestion__stream__pb2.SubscribeDataEventRequest.FromString,
                    response_serializer=ingestion__stream__pb2.SubscribeDataEventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dp.service.ingestionstream.DpIngestionStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dp.service.ingestionstream.DpIngestionStreamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DpIngestionStreamService(object):
    """
    ------------------- RPC Interfaces ---------------------------



    The Ingestion Stream Service Interface

    Defines RPC operations for processing of the ingestion data stream.

    """

    @staticmethod
    def subscribeDataEvent(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/dp.service.ingestionstream.DpIngestionStreamService/subscribeDataEvent',
            ingestion__stream__pb2.SubscribeDataEventRequest.SerializeToString,
            ingestion__stream__pb2.SubscribeDataEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
