# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import query_pb2 as query__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in query_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DpQueryServiceStub(object):
    """
    ------------------- RPC Interfaces ---------------------------



    The Query Service Interface

    Defines RPC operations for data and metadata queries.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.queryData = channel.unary_unary(
                '/dp.service.query.DpQueryService/queryData',
                request_serializer=query__pb2.QueryDataRequest.SerializeToString,
                response_deserializer=query__pb2.QueryDataResponse.FromString,
                _registered_method=True)
        self.queryDataStream = channel.unary_stream(
                '/dp.service.query.DpQueryService/queryDataStream',
                request_serializer=query__pb2.QueryDataRequest.SerializeToString,
                response_deserializer=query__pb2.QueryDataResponse.FromString,
                _registered_method=True)
        self.queryDataBidiStream = channel.stream_stream(
                '/dp.service.query.DpQueryService/queryDataBidiStream',
                request_serializer=query__pb2.QueryDataRequest.SerializeToString,
                response_deserializer=query__pb2.QueryDataResponse.FromString,
                _registered_method=True)
        self.queryTable = channel.unary_unary(
                '/dp.service.query.DpQueryService/queryTable',
                request_serializer=query__pb2.QueryTableRequest.SerializeToString,
                response_deserializer=query__pb2.QueryTableResponse.FromString,
                _registered_method=True)
        self.queryPvMetadata = channel.unary_unary(
                '/dp.service.query.DpQueryService/queryPvMetadata',
                request_serializer=query__pb2.QueryPvMetadataRequest.SerializeToString,
                response_deserializer=query__pb2.QueryPvMetadataResponse.FromString,
                _registered_method=True)
        self.queryProviders = channel.unary_unary(
                '/dp.service.query.DpQueryService/queryProviders',
                request_serializer=query__pb2.QueryProvidersRequest.SerializeToString,
                response_deserializer=query__pb2.QueryProvidersResponse.FromString,
                _registered_method=True)
        self.queryProviderMetadata = channel.unary_unary(
                '/dp.service.query.DpQueryService/queryProviderMetadata',
                request_serializer=query__pb2.QueryProviderMetadataRequest.SerializeToString,
                response_deserializer=query__pb2.QueryProviderMetadataResponse.FromString,
                _registered_method=True)


class DpQueryServiceServicer(object):
    """
    ------------------- RPC Interfaces ---------------------------



    The Query Service Interface

    Defines RPC operations for data and metadata queries.
    """

    def queryData(self, request, context):
        """
        queryData: Unary (non-streaming) time series data query.

        Client sends a single QueryDataRequest with the query parameters, and receives a single QueryDataResponse with the
        query results. The response may indicate rejection, error in handling, no data matching query, or otherwise
        contains the data matching the query specification.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def queryDataStream(self, request, context):
        """
        queryDataStream: Server-side streaming time series data query.

        Client sends a single QueryDataRequest with the query parameters, and receives a stream of QueryDataResponse
        messages with the query results. The response may indicate rejection, error in handling, no data matching query,
        or otherwise contains the data matching the query specification.  Results are sent in the response stream until
        the MongoDB cursor for the query is exhausted, or an error is encountered in processing.

        The response stream is closed by the server in case of rejection, if there is an error in processing, or the
        result cursor is exhausted.

        We expect this to be the best performing RPC for time series data query.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def queryDataBidiStream(self, request_iterator, context):
        """
        queryDataBidiStream: Bidirectional streaming time series data query.

        Client sends a QueryDataRequest with the query parameters, and receives an initial QueryDataResponse message
        with the query results.

        While the MongoDB cursor for the query result contains additional details, the client sends a QueryDataRequest
        message with a CursorOperation payload to receive the next QueryDataResponse message in the stream.  This should
        continue in a loop until the query result is exhausted.

        The server closes the response stream if a request is rejected, or when the result is exhausted or an error
        is encountered.

        Each individual response may indicate rejection, error in handling, no data matching query, or otherwise
        contains the data matching the query specification.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def queryTable(self, request, context):
        """
        queryTable: Unary (non-streaming) time series data query with tabular result.

        This time series data query returns its result in a tabular format, for use by the Data Platform web application.
        The client sends a single QueryTableRequest with the query parameters and receives a single QueryTableResponse.
        The response content may indicate an exception in handling such as rejection, database error, no data matching
        query, or otherwise contains the tabular data matching the query specification.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def queryPvMetadata(self, request, context):
        """
        queryPvMetadata(): Unary (non-streaming) metadata query.

        This RPC is used by clients to learn about data sources (PVs/columns) available in the archive.  Client sends
        a single QueryPvMetadataRequest with the query parameters, and receives a single QueryPvMetadataResponse
        with the query results. The response may indicate rejection, error in handling, no data matching query, or
        otherwise contains the data matching the query specification.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def queryProviders(self, request, context):
        """
        queryProviders(): Unary Providers query.

        This rpc is used by clients to retrieve details about ingestion data Providers defined in the archive.
        It accepts a single "QueryProvidersRequest" containing the query parameters and returns a single
        "QueryProvidersResponse".  The response may indicate an exceptional result such as rejection or error in handling
        the request, otherwise it contains information about each Provider matching the query criteria.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def queryProviderMetadata(self, request, context):
        """
        queryProviderMetadata(): Unary Provider metadata query.

        This rpc is used by clients to retrieve ingestion statistics for data Providers defined in the archive.
        It accepts a single "QueryProviderMetadataRequest" message containing the query parameters, and returns a single
        "QueryProviderMetadataResponse".  The response may indicate an exceptional result such as rejection or error in
        handling the request, otherwise it contains ingestion metadata for the specified data provider.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DpQueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'queryData': grpc.unary_unary_rpc_method_handler(
                    servicer.queryData,
                    request_deserializer=query__pb2.QueryDataRequest.FromString,
                    response_serializer=query__pb2.QueryDataResponse.SerializeToString,
            ),
            'queryDataStream': grpc.unary_stream_rpc_method_handler(
                    servicer.queryDataStream,
                    request_deserializer=query__pb2.QueryDataRequest.FromString,
                    response_serializer=query__pb2.QueryDataResponse.SerializeToString,
            ),
            'queryDataBidiStream': grpc.stream_stream_rpc_method_handler(
                    servicer.queryDataBidiStream,
                    request_deserializer=query__pb2.QueryDataRequest.FromString,
                    response_serializer=query__pb2.QueryDataResponse.SerializeToString,
            ),
            'queryTable': grpc.unary_unary_rpc_method_handler(
                    servicer.queryTable,
                    request_deserializer=query__pb2.QueryTableRequest.FromString,
                    response_serializer=query__pb2.QueryTableResponse.SerializeToString,
            ),
            'queryPvMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.queryPvMetadata,
                    request_deserializer=query__pb2.QueryPvMetadataRequest.FromString,
                    response_serializer=query__pb2.QueryPvMetadataResponse.SerializeToString,
            ),
            'queryProviders': grpc.unary_unary_rpc_method_handler(
                    servicer.queryProviders,
                    request_deserializer=query__pb2.QueryProvidersRequest.FromString,
                    response_serializer=query__pb2.QueryProvidersResponse.SerializeToString,
            ),
            'queryProviderMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.queryProviderMetadata,
                    request_deserializer=query__pb2.QueryProviderMetadataRequest.FromString,
                    response_serializer=query__pb2.QueryProviderMetadataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dp.service.query.DpQueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dp.service.query.DpQueryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DpQueryService(object):
    """
    ------------------- RPC Interfaces ---------------------------



    The Query Service Interface

    Defines RPC operations for data and metadata queries.
    """

    @staticmethod
    def queryData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dp.service.query.DpQueryService/queryData',
            query__pb2.QueryDataRequest.SerializeToString,
            query__pb2.QueryDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def queryDataStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dp.service.query.DpQueryService/queryDataStream',
            query__pb2.QueryDataRequest.SerializeToString,
            query__pb2.QueryDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def queryDataBidiStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/dp.service.query.DpQueryService/queryDataBidiStream',
            query__pb2.QueryDataRequest.SerializeToString,
            query__pb2.QueryDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def queryTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dp.service.query.DpQueryService/queryTable',
            query__pb2.QueryTableRequest.SerializeToString,
            query__pb2.QueryTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def queryPvMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dp.service.query.DpQueryService/queryPvMetadata',
            query__pb2.QueryPvMetadataRequest.SerializeToString,
            query__pb2.QueryPvMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def queryProviders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dp.service.query.DpQueryService/queryProviders',
            query__pb2.QueryProvidersRequest.SerializeToString,
            query__pb2.QueryProvidersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def queryProviderMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dp.service.query.DpQueryService/queryProviderMetadata',
            query__pb2.QueryProviderMetadataRequest.SerializeToString,
            query__pb2.QueryProviderMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
